version: "3.8"
services:

  api:
    image: sit-careers-api:local
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile-local
    working_dir: /app
    container_name: sit-careers-api
    restart: always
    volumes:
      - ./:/app
    entrypoint:
      - ./docker/api/entrypoint.local.sh
    ports:
      - "8000:8000"
    depends_on:
      - composer
    networks:
      - sit-careers

  composer:
    image: sit-careers-api:local
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile-local
    working_dir: /app
    container_name: sit-careers-composer
    entrypoint:
      - ./docker/api/composer.sh
    volumes:
      - ./:/app
    networks:
      - sit-careers

  db:
    image: mariadb:latest
    restart: always
    container_name: sit-careers-db
    volumes:
        - ./db:/var/lib/mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_DATABASE: sitcareers
        MYSQL_ROOT_PASSWORD: root
    networks:
        - sit-careers

  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      restart: always
      container_name: sit-careers-myadmin
      ports:
          - "8080:80"
      environment:
          PMA_HOST: db
          MYSQL_ROOT_PASSWORD: root
      depends_on:
          - db
      networks:
          - sit-careers

networks:
  sit-careers:
    driver: bridge
